version: '3.4'

services:
  
  api:
    container_name: efpoc_api
    image: ${REGISTRY:-efpoc}/api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - database
    
  database:
    container_name: efpoc_database
    image: ${REGISTRY:-efpoc}/database:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Database/Dockerfile
    ports:
      - "5434:1433"