version: '3.4'

services:

  database:
    container_name: efpoc_database
    image: ${REGISTRY:-efpoc}/database:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Database/Dockerfile
    ports:
      - "1433:1433"